import { StyleSheet, Dimensions } from "react-native";

const { width: windowWidth, height: windowHeight } = Dimensions.get("window");

export const entriesStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F5F5",
    paddingTop: 60,
    marginTop: 20,
  },
  content: {
    flex: 1,
    alignItems: "center",
    paddingHorizontal: 20,
    justifyContent: "flex-start",
    paddingTop: 10,
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    textAlign: "center",
    color: "#333",
    marginBottom: 20,
    marginTop: 10,
  },
  statisticsTitle: {
    fontSize: 20,
    fontWeight: "600",
    textAlign: "center",
    color: "#333",
    marginTop: 20,
    marginBottom: 10,
  },
  statisticsText: {
    fontSize: 15,
    textAlign: "center",
    color: "#666",
    marginHorizontal: 20,
    marginBottom: 20,
    lineHeight: 22,
  },
  formContainer: {
    width: "100%",
    // height: "50%",
    backgroundColor: "#fff",
    borderRadius: 15,
    padding: 20,
    marginTop: 10,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  inputLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#333",
    marginTop: 12,
    marginBottom: 10,
    marginLeft: 4,
  },
  inputContainer: {
    backgroundColor: "#f8f9fa",
    borderRadius: 10,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    paddingHorizontal: 15,
    paddingVertical: 12,
    fontSize: 16,
    color: "#333",
  },
  button: {
    width: Dimensions.get("window").width * 0.8,
    backgroundColor: "#52B788",
    borderRadius: 25,
    paddingVertical: 15,
    paddingHorizontal: 30,
    marginTop: 20,
    marginBottom: 10,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#52B788",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  buttonText: {
    fontSize: 17,
    fontWeight: "bold",
    color: "white",
    textAlign: "center",
    letterSpacing: 0.5,
  },
  cancelButton: {
    backgroundColor: "#6c757d",
    shadowColor: "#6c757d",
    marginBottom: 30,
  },
  inventoryList: {
    width: Dimensions.get("window").width * 0.95,
  },
  entry: {
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 15,
    marginBottom: 12,
    marginHorizontal: 10,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.08,
    shadowRadius: 3,
    elevation: 3,
  },
  item: {
    fontSize: 18,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 5,
  },
  barcode: {
    fontSize: 14,
    color: "#777",
    marginBottom: 5,
  },
  subButton: {
    borderRadius: 10,
    marginTop: 10,
    paddingVertical: 10,
    paddingHorizontal: 20,
    alignItems: "center",
    justifyContent: "center",
    width: "48%",
  },
  subButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "white",
  },
  deleteButton: {
    backgroundColor: "#FF5261",
  },
  editButton: {
    backgroundColor: "#FFB300",
  },
  datePickerButton: {
    backgroundColor: "#f8f9fa",
    paddingVertical: 14,
    paddingHorizontal: 15,
    borderRadius: 10,
    marginBottom: 10,
    borderWidth: 1,
    borderColor: "#e0e0e0",
    alignItems: "center",
    justifyContent: "center",
  },

  datePickerText: {
    fontSize: 16,
    color: "#333",
    textAlign: "center",
  },

  expiry: {
    fontSize: 14,
    marginTop: 5,
    fontWeight: "500",
  },

  dateAdded: {
    fontSize: 12,
    marginTop: 3,
    color: "#888",
    fontStyle: "italic",
  },

  quantity: {
    fontSize: 14,
    color: "#666",
    marginBottom: 3,
  },
});
