import { StyleSheet, Dimensions } from "react-native";

const { width: windowWidth, height: windowHeight } = Dimensions.get("window");

export const settingsStyles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: "#F5F5F5",
    padding: 20,
    paddingTop: 80,
    alignItems: "center",
  },
  safeAreaView: {
    flex: 1,
    backgroundColor: "#F5F5F5",
  },
  title: {
    fontSize: 28,
    fontWeight: "bold",
    color: "#333",
    marginBottom: 40,
    textAlign: "center",
  },
  userInfoContainer: {
    width: "100%",
    backgroundColor: "#fff",
    borderRadius: 12,
    paddingHorizontal: 20,
    paddingVertical: 20,
    marginBottom: 30,
    shadowColor: "#000",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.1,
    shadowRadius: 3.84,
    elevation: 5,
  },
  emailLabel: {
    fontSize: 14,
    fontWeight: "600",
    color: "#666",
    marginBottom: 5,
  },
  emailText: {
    fontSize: 16,
    color: "#333",
    marginBottom: 10,
  },
  emailVerificationText: {
    fontSize: 14,
    color: "#FF9800",
    fontWeight: "500",
    marginTop: 5,
  },
  verifyButton: {
    backgroundColor: "#52B788",
    paddingVertical: 10,
    paddingHorizontal: 20,
    borderRadius: 20,
    marginTop: 12,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#52B788",
    shadowOffset: {
      width: 0,
      height: 2,
    },
    shadowOpacity: 0.2,
    shadowRadius: 3,
    elevation: 3,
  },
  verifyButtonText: {
    fontSize: 14,
    fontWeight: "600",
    color: "white",
    letterSpacing: 0.3,
  },
  logoutButton: {
    backgroundColor: "#FF5252",
    width: windowWidth * 0.85,
    paddingVertical: 15,
    borderRadius: 25,
    marginBottom: 15,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#FF5252",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  logoutAllButton: {
    backgroundColor: "#D32F2F",
    width: windowWidth * 0.85,
    paddingVertical: 15,
    borderRadius: 25,
    alignItems: "center",
    justifyContent: "center",
    shadowColor: "#D32F2F",
    shadowOffset: {
      width: 0,
      height: 3,
    },
    shadowOpacity: 0.3,
    shadowRadius: 4,
    elevation: 4,
  },
  buttonText: {
    fontSize: 17,
    fontWeight: "bold",
    color: "white",
    letterSpacing: 0.5,
  },
  legalSection: {
    width: "100%",
    marginTop: 30,
    paddingTop: 20,
    borderTopWidth: 1,
    borderTopColor: "#E0E0E0",
  },
  legalTitle: {
    fontSize: 18,
    fontWeight: "600",
    color: "#333",
    marginBottom: 15,
    textAlign: "center",
  },
  legalLink: {
    paddingVertical: 12,
    paddingHorizontal: 20,
    marginBottom: 10,
    alignItems: "center",
  },
  legalLinkText: {
    fontSize: 15,
    color: "#5295B7",
    textDecorationLine: "underline",
  },
});